name: PSEC
channels:
  - defaults
dependencies:
  - _libgcc_mutex=0.1
  - _openmp_mutex=5.1
  - ca-certificates=2024.11.26
  - ld_impl_linux-64=2.40
  - libffi=3.4.4
  - libgcc-ng=11.2.0
  - libgomp=11.2.0
  - libstdcxx-ng=11.2.0
  - ncurses=6.4
  - openssl=3.0.15
  - pip=24.2
  - python=3.9.21
  - readline=8.2
  - sqlite=3.45.3
  - tk=8.6.14
  - wheel=0.44.0
  - xz=5.4.6
  - zlib=1.2.13
  - pip:
      - absl-py==2.1.0
      - annotated-types==0.7.0
      - asttokens==3.0.0
      - attrs==24.3.0
      - backcall==0.2.0
      - beautifulsoup4==4.12.3
      - bleach==6.2.0
      - bullet-safety-gym==1.4.0
      - certifi==2024.12.14
      - charset-normalizer==3.4.1
      - chex==0.1.88
      - click==8.1.8
      - cloudpickle==3.1.0
      - contextlib2==21.6.0
      - contourpy==1.3.0
      - cycler==0.12.1
      - decorator==5.1.1
      - defusedxml==0.7.1
      - dm-tree==0.1.8
      - docker-pycreds==0.4.0
      - docopt==0.6.2
      - dsrl==0.1.0
      - etils==1.5.2
      - eval-type-backport==0.2.2
      - exceptiongroup==1.2.2
      - executing==2.1.0
      - farama-notifications==0.0.4
      - fastjsonschema==2.21.1
      - flax==0.8.5
      - fonttools==4.55.3
      - fsspec==2024.12.0
      - gast==0.6.0
      - gitdb==4.0.11
      - gitpython==3.1.43
      - glfw==2.8.0
      - gym==0.26.2
      - gym-notices==0.0.8
      - gymnasium==0.28.1
      - h5py==3.12.1
      - humanize==4.11.0
      - idna==3.10
      - imageio==2.36.1
      - importlib-metadata==8.5.0
      - importlib-resources==6.4.5
      - iniconfig==2.0.0
      - ipython==8.12.3
      - jax==0.4.30
      - jax-cuda12-pjrt==0.4.30
      - jax-cuda12-plugin==0.4.30
      - jax-jumpy==1.0.0
      - jaxlib==0.4.30
      - jedi==0.19.2
      - jinja2==3.1.5
      - jsonschema==4.23.0
      - jsonschema-specifications==2024.10.1
      - jupyter-client==8.6.3
      - jupyter-core==5.7.2
      - jupyterlab-pygments==0.3.0
      - kiwisolver==1.4.7
      - llvmlite==0.43.0
      - lxml==5.3.0
      - markdown-it-py==3.0.0
      - markupsafe==3.0.2
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - metadrive-simulator==0.2.6.0
      - mistune==3.1.0
      - ml-collections==0.1.1
      - ml-dtypes==0.5.0
      - msgpack==1.1.0
      - mujoco==2.3.0
      - nbclient==0.10.2
      - nbconvert==7.16.5
      - nbformat==5.10.4
      - nest-asyncio==1.6.0
      - numba==0.60.0
      - numpy==1.26.4
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvcc-cu12==12.6.85
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.6.0.74
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-nccl-cu12==2.23.4
      - nvidia-nvjitlink-cu12==12.6.85
      - opencv-python-headless==4.11.0.86
      - opt-einsum==3.4.0
      - optax==0.2.4
      - orbax-checkpoint==0.6.4
      - packaging==24.2
      - panda3d==1.10.8
      - panda3d-gltf==1.2.1
      - panda3d-simplepbr==0.12.0
      - pandas==2.2.3
      - pandocfilters==1.5.1
      - parso==0.8.4
      - pexpect==4.9.0
      - pickleshare==0.7.5
      - pillow==11.0.0
      - pipreqs==0.5.0
      - platformdirs==4.3.6
      - pluggy==1.5.0
      - prompt-toolkit==3.0.50
      - protobuf==3.20.1
      - psutil==6.1.1
      - ptyprocess==0.7.0
      - pure-eval==0.2.3
      - pybullet==3.2.6
      - pydantic==2.10.4
      - pydantic-core==2.27.2
      - pygame==2.1.0
      - pygments==2.18.0
      - pyopengl==3.1.7
      - pyparsing==3.2.0
      - pytest==8.3.4
      - python-dateutil==2.9.0.post0
      - pytz==2024.2
      - pyyaml==6.0.2
      - pyzmq==26.2.0
      - referencing==0.36.1
      - requests==2.32.3
      - rich==13.9.4
      - rpds-py==0.22.3
      - safety-gymnasium==0.4.0
      - scipy==1.13.1
      - seaborn==0.13.2
      - sentry-sdk==2.19.2
      - setproctitle==1.3.4
      - setuptools==64.0.3
      - six==1.17.0
      - smmap==5.0.1
      - soupsieve==2.6
      - stack-data==0.6.3
      - tensorboardx==2.6.2.2
      - tensorflow-probability==0.21.0
      - tensorstore==0.1.69
      - tinycss2==1.4.0
      - tomli==2.2.1
      - toolz==1.0.0
      - tornado==6.4.2
      - tqdm==4.67.1
      - traitlets==5.14.3
      - typing-extensions==4.12.2
      - tzdata==2024.2
      - urllib3==2.3.0
      - vulture==2.14
      - wandb==0.19.1
      - wcwidth==0.2.13
      - webencodings==0.5.1
      - xmltodict==0.14.2
      - yapf==0.43.0
      - yarg==0.1.9
      - zipp==3.21.0
prefix: /home/root/anaconda3/envs/PSEC
